[package]
name = "dairyshop"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { version = "0.37.5", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
